version: "3"
services:
  hazelcast-server:
    image: hazelcast/hazelcast:5.1.1
    ports:
      - "5701:5701"
  management-center:
    image: hazelcast/management-center:5.1.1
    ports: 
      - "8081:8080"
    environment:
      MC_DEFAULT_CLUSTER_MEMBERS: hazelcast-server
  jmixapp:
    image: jmix-hazelcast:latest
    ports:
      - "8080:8080"

